### ISSUE TITLE
Change Wallpaper to Custom Image

### ISSUE THREAD

**Issue by psmis2** [Enrico204/Whatsapp-Desktop#36]
Is there a way to use personalized images? There is no instructions in how to do so with CSS or via the Settings

**Comment by Enrico204** [comment]
Hi @psmis2 , there is no option for that in Settings (not yet, anyway). In CSS you can apply `background-image` and `opacity` attributes to `pane-chat-tile` class, for example:

    .pane-chat-tile {
       background-image: url(http://d3i6fh83elv35t.cloudfront.net/newshour/wp-content/uploads/2015/07/Western_Union-1024x735.jpg);
       opacity: 0.5;
    }

PS: I didn't tested it, you may need to use "!important" to have this setting applied.

**Comment by psmis2** [comment]
Using the above CSS results in the original chat image disappearing, leaving only the default solid color background.

**Comment by psmis2** [comment]
I arrived at a working state with
```
.pane-chat-tile {
   background-image: url(https://localhost/th.jpg) !important;
   background-size: cover !important;
   opacity: 1 !important; 
  max-width: 100% !important;
}
```
although the manner this works is extremely "hackish". Due to #38 and #37 I had to switch over to the Windows version to debug. The conclusions I arrived:

- Using an image served through HTTP will not work due to it not being loaded over SSL/HTTPS.
- The above code first suggested actually works but with another image url (tried with one from alpha.wallhaven.cc, developer tools complained something about SSL with the original URL, must have been a server with exotic ssl settings).
- Using a self-signed certificate will also result in the image not loading. There is no warning of this, only developer tool console complaining about it.

A workaround for using self-signed certificates involved adding the certificate I generated to the trusted list in ~/.pki/nssdb

**Comment by Enrico204** [comment]
Thanks for your tests! Yes, that snippet loads images only from HTTPS locations (this is due to HTTPS protocol used for loading whatsapp web app). I tried with some HTTPS locations and it works. Self-signed certificates doesn't work (of course) and there is no warning nor a confirmation request due to the fact that self-signed certs should not be used anymore (see letsencrypt.org).

Still, for people that doesn't know CSS these tricks are unusable. I think that I'll be able to build an interface to load the image, convert to base64 and embed into the page (so, no SSL issues).

**Comment by Enrico204** [comment]
I've implemented a selector into settings panel for local images :-)
