### ISSUE TITLE
Flatpak or AppImage 

### ISSUE THREAD

**Issue by jor1196** [Enrico204/Whatsapp-Desktop#56]
It would not be a bad idea if WSP Desktop were available in one of those two formats (I personally prefer flatpak), this could make the development and publication of the same more efficient. And each one can be available in their corresponding repositories, Flathub for flatpak, Bintray for AppImage, depending on which one is chosen

**Comment by jor1196** [comment]
First of all, both seek the "applications independence" of the distributions
AppImage focuses more on the portability of the application, with a click, execute and go. The necessary libraries are in the same AppImage of the application and you can not share them with another one. The security is not well defined but it can be executed with FireJail (sandbox) to cover that problem
Flatpak looks for the security and the sandbox of the application before the distribution. It consists of Runtimes that are a set of libraries, with different versions depending on the applications and can be shared. There are many applications available in this format like Spotify

**Comment by Enrico204** [comment]
Ok, I think that I'll look at its documentation soon :-)

**Comment by jor1196** [comment]
I've thought it better, I think the best solution is Snap
I rely on the Solus team's thinking when selecting Snap instead of Flatpak and it's very true
It spends a lot of space in the .Platform and .Sdk, I do not think that a user ends up installing applications that use them completely

**Comment by giovannicaligaris** [comment]
You should make a flatpak and host it on Flathub

https://flathub.org/

That way your app can be used in any Linux distro!

Right now Gnome Sofware Center and a few others have support for flatpak apps.

**Comment by Enrico204** [comment]
Ok then, I'll work on it for next milestone :-)

**Comment by jor1196** [comment]
you will need the org.freedesktop.Platform to build your flatpak

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by giovannicaligaris** [comment]
I personally prefer flatpaks because it is much easier to update the app. With Appimages you have to chase the next release, unless I am completely wrong.

**Comment by probonopd** [comment]
Indeed you are wrong, in fact it is very easy using [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) (and, since recently, libappimageupdate).

**Comment by Enrico204** [comment]
Ok today I had some free time to study how AppImage and Flatpak works. I do not agree with all of those (and, maybe, you too) which says that these *systems* are *the solution* for what Linus said at DebConf'14 about linux desktop fragmentation.

Yes, we have a problem with system versions, library versions and *so on and so forth*. The core of this problem is named "library". **Libraries (developers) changes ABI/API, breaking backward compatibility**. So, you need to recompile many times for different platforms, and sometimes you need also to have conditional compiling and/or code adjustment to be able to compile binary software for different platforms.

Yet, embedding libraries as AppImage and Flatpak do, is very bad: a gazillion of different library versions are running at the same time in the same PC, so 1) no memory/code reuse, 2) more RAM needed (which is very bad if you already have some bad guys like Electron running). But the worst thing is that **if there is a security update** for a library, **every AppImage/Flatpak need to be rebuilt** and redistribuited. This is not needed when a package manager (such as `apt`) update a single library shared by many software (let's say, `openssl`).

For me, **security is better than comfort** even in development. I see nothing wrong in current scenario, where many distributions have their own way to update things. **I see bad behavior of developers** who changes APIs very rapidly (do you want an example? **NodeJS**).

If we want to became like *macOS* or (better) *Windows* on supporting applications cross-versions (as Linus want to), developers needs to stop changing signatures for functions/objects. For example, tray icon APIs are a nightmare thru different version of GNOME/Ubuntu (**the same f*king desktop environment**).

Said this, as I can't choose which one of two is better, I made Travis-CI to build both of them :-D

If the script is working, you'll find AppImage and Flatpak files attached to the next release (0.4.1).

Happy new year :-)

**Comment by probonopd** [comment]
° If we want to became like macOS or (better) Windows on supporting applications cross-versions (as Linus want to), developers needs to stop changing signatures for functions/objects.

Exactly. To make "Desktop Linux" a viable platform (as in: Windows, macOS) to develop against, we need to overcome those challenges. https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues
