### ISSUE TITLE
[Feature Request] Minimize to tray on startup 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [Enrico204/Whatsapp-Desktop#7]

**Comment by Enrico204** [comment]
Done :-)

**Comment by ceyhunnabiyev** [comment]
Thanks a lot :+1:

**Comment by ceyhunnabiyev** [comment]
@Enrico204, please release new version in order to get important features (#4,#6,#7)  still I have 0.3.6 (AUR) .

**Comment by Enrico204** [comment]
@bil-elmoussaoui is the maintainer of AUR package, I think that he will update it asap ;-)
PS: I've just released version 0.3.9 with all these features

**Comment by ceyhunnabiyev** [comment]
@Enrico204 , 
That is strange. I launch Whatsapp-desktop, Minimizing to tray on startup  works. However I copy whatapp.desktop file to autostart folder in Gnome DE,  minimizing to tray on startup doesn't work after restart or logout. Can I miss something?

**Comment by Enrico204** [comment]
Maybe the autostart is executed two times. The second time the application is programmed to show the main window of the running instance instead of re-launch itself.
I don't have an ArchLinux installation for testing, I'll try to setup it when I have time.

PS: maybe Gnome is re-opening last session? In other words, if a software was running on logout, gnome restart it on login? That may explain the double-launch that might result in your behaviour.

**Comment by ceyhunnabiyev** [comment]
Can you add option to make the app boot on system startup like Facebook Messenger Desktop. İ have no problem with facebook messenger boot.

Regards...

**Comment by Enrico204** [comment]
As this feature is working, and that is an incompatibility with that DE/Distribution, I'm closing this issue and opening a new one #8

**Comment by bil-elmoussaoui** [comment]
The AUR package was updated to 0.3.10

**Comment by Enrico204** [comment]
thanks @bil-elmoussaoui :-)
