### ISSUE TITLE
Whatsapp-Desktop Settings on macOS

### ISSUE THREAD

**Issue by Defrilitus** [Enrico204/Whatsapp-Desktop#70]
### System details

* OS: [macOS 10.13.2]
* App Version: [github]

A few questions, as all Whatsapp-Desktop settings are stated to be platform-independent:
- "Show tray icon" and "Minimize to tray" would appear to have no functionality on a Mac, as there is no tray in macOS.
- What is "Auto-hide menu bar" supposed to do (it certainly doesn't hide the menu bar on a Mac)?
- Advantages/disadvantages relating to "Disable GPU"? The README isn't of much help.

Thanks in advance.

**Comment by Enrico204** [comment]
* "Show tray icon" and "Minimize to tray" should have an effect on system tray (eg. icons near clock). I'm not a macOS user, so maybe this behavior is changed since I used macOS.
* You're right, this feature is a non-sense on macOS. I'd better to specify it.
* Actually, "Disable GPU" is/was useful when dealing with bugged video drivers (maybe this is very rare on macOS)

I'll update the README to better specify these items :-)

**Comment by Defrilitus** [comment]
Thanks for your quick reply. I sort of figured that you weren't a Mac user ;-)
The Windows system tray doesn't really have an equivalent on macOS (though there are some similarities between the Windows tray and the Mac menu bar), so tray settings won't work on a Mac.
In any case, if you need someone to do testing on a Mac, please feel free to contact me directly; I'd be pleased to help.
Keep up the good work!

**Comment by Enrico204** [comment]
Let's continue on #71 :-)
